### PR TITLE
Deep copy lite

### PR DESCRIPTION
**Pull request by nealrichardson**
Send a derivation + derived: false. This makes many things better for our users and for our servers. Previously, `copy(..., deep=TRUE)` returned a `VariableDefinition` with values and metadata; now, it returns a derivation and less metadata. 

_As it turns out_, there are a few tests that need to be updated because they munged payloads that have now changed. https://github.com/Crunch-io/rcrunch/compare/deep-copy-lite#diff-bc0b7f61a973b28ec42cca1d898d61c0R81 fixes one; https://ci.crunch.io/job/gen3-rcrunch-functional-tests/6235/testReport/junit/ identifies the three remaining tests that need updating.

### CODE REVIEW

**Comment by GShotwell** [comment]
Some more detail on the test failures: 
```
Failed -------------------------------------------------------------------------
1. Failure: Deep copies don't get data when appending (@test-deep-copy-variable.R#42) 
as.array(crtabs(~q1, data = out)) not equivalent to 2 * as.array(crtabs(~q1a, data = out)).
Attributes: < Component "dimnames": Names: 1 string mismatch >


2. Failure: Deep copies don't get data when appending (@test-deep-copy-variable.R#44) 
as.array(crtabs(~petloc, data = out)) not equivalent to 2 * as.array(crtabs(~petloca, data = out)).
Attributes: < Component "dimnames": Names: 2 string mismatches >


3. Failure: When appending, derived arrays get data (or missing, as appropriate) (@test-derive-array.R#140) 
names(categories(ds$metapetloc)) not identical to c(...).
Lengths differ: 7 vs 8


4. Failure: When appending, derived arrays get data (or missing, as appropriate) (@test-derive-array.R#146) 
as.numeric(table(ds$metapetloc[[2]])) not identical to c(5, 3, 3, 0, 0).
3/5 mismatches (average diff: 3.67)
[1] 10 - 5 == 5
[2]  6 - 3 == 3
[3]  6 - 3 == 3


5. Failure: When appending, derived arrays get data (or missing, as appropriate) (@test-derive-array.R#149) 
as.numeric(table(ds$metapetloc[[3]])) not identical to c(6, 4, 6, 0, 0).
3/5 mismatches (average diff: 5.33)
[1] 12 - 6 == 6
[2]  8 - 4 == 4
[3] 12 - 6 == 6


6. Failure: Combined categories on top of derived array also gets the right data (@test-derive-array.R#163) 
names(categories(ds$metapet_combined)) not identical to c("Cat", "Dog", "Bird", "Skipped", "Not Asked", "No Data").
Lengths differ: 5 vs 6


7. Failure: Combined categories on top of derived array also gets the right data (@test-derive-array.R#167) 
as.numeric(table(ds$metapet_combined[[2]])) not identical to c(5, 3, 3).
3/3 mismatches (average diff: 3.67)
[1] 10 - 5 == 5
[2]  6 - 3 == 3
[3]  6 - 3 == 3


8. Failure: Combined categories on top of derived array also gets the right data (@test-derive-array.R#169) 
as.numeric(table(ds$metapet_combined[[3]])) not identical to c(6, 4, 6).
3/3 mismatches (average diff: 5.33)
[1] 12 - 6 == 6
[2]  8 - 4 == 4
[3] 12 - 6 == 6


9. Failure: There are no test code errors --------------------------------------
stop(e$message) threw an error.
subscript out of bounds


10. Failure: There are no test code errors -------------------------------------
stop(e$message) threw an error.
Client error: (400) Bad Request: There was a problem with your derivation expression


11. Error: Can create dataset with data in S3 (@test-new-dataset.R#175) --------
s3://testing-crunch-io/example-dataset.csv not found
1: createWithMetadataAndFile(m, file = "s3://testing-crunch-io/example-dataset.csv") at testthat/test-new-dataset.R:175
2: uploadData(ds, file, strict, first_batch = TRUE)
3: addBatchFile(dataset, data, strict = strict, first_batch = TRUE)
4: addBatch(dataset, url = file, ...)
5: do_it({
       body <- wrapEntity(body = body)
       suppressMessages(crPOST(batches_url, body = toJSON(body)))
   })
6: tryCatch(eval(expr), error = function(e) {
       with_consent(delete(ds))
       stop(e)
   })
7: tryCatchList(expr, classes, parentenv, handlers)
8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
9: value[[3L]](cond)

12. Failure: If No Data isn't a category, it is added automatically to array (@test-update-with-missing.R#110) 
ids(categories(ds$petloc2)) not equal to c(1, 2, 3, 8, 9).
Lengths differ: 6 vs 5


13. Error: If No Data isn't a category, it is added automatically to array (@test-update-with-missing.R#111) 
Client error: (400) Bad Request: Cannot update derived variable 3ea4dd3f0fba42989b06a31c4469b24a.
1: `[<-`(`*tmp*`, 5, value = NA) at testthat/test-update-with-missing.R:111
2: `[<-`(`*tmp*`, 5, value = NA)
3: .local(x, i, j, ..., value)
4: .categorical.update[["numeric"]](x, i, j, value)
5: .updateVariable(x, value, filter = .dispatchFilter(i))
6: crPOST(update_url, body = toJSON(payload))
7: crunchAPI("POST", ...)
8: handleAPIresponse(x, special.statuses = status.handlers)
9: halt(msg)
10: stop(..., call. = call.)
```

**Comment by nealrichardson** [comment]
One note but otherwise LGTM. Please confirm that you've run the relevant integration tests with these changes.

**Comment by GShotwell** [comment]
Great, that change has been made and all tests pass against stable.

**Comment by nealrichardson** [comment]
Ok. Last final things:

1. According to the coverage report, we need to add a mock test for deep copy. Could make a `copy(var, deep=TRUE)` and assert that it has `derived=FALSE` in the body.
2. Please add NEWS that we've made deep copying more efficient.

**Comment by nealrichardson** [comment]
🎉 💯

**Pull request merged**
